
# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

#####################
# longhorn subchart
#####################

longhorn:
  defaultSettings:
    defaultDataPath: "/storage"


