
# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

#####################
# longhorn subchart
#####################

longhorn:
  defaultSettings:
    defaultReplicaCount: 2
    replicaAutoBalance: best-effort
    replicaSoftAntiAffinity: false
    allowVolumeCreationWithDegradedAvailability: false
    guaranteedEngineManagerCPU: 20
    guaranteedReplicaManagerCPU: 20
    priorityClass: high-priority
  persistence:
    defaultClassReplicaCount: 2
